### ISSUE TITLE
Unable to fetch content files

### ISSUE THREAD

**Issue by madjin** [meta-quest/ProjectFlowerbed#1]
Greetings, first wanna give props for providing a great project + case study on WebXR 😤👍

Been having difficult fetching the content files. At first I thought something was broken because the blends didn't open anything and the glTF files missing textures and PNGs didn't open in image viewer, then realized I needed `git-lfs` (should be noted in the README). I've tried installing git-lfs, doing git lfs pull / fetch / clone / checkout, and get errors like this:

![image](https://user-images.githubusercontent.com/32600939/221374419-7aba6847-caa9-49f9-a439-f40677dd26dd.png)

![image](https://user-images.githubusercontent.com/32600939/221374410-23ba554d-7592-4084-9307-e09b1b84503a.png)

Am I doing something wrong? I'm using Windows + WSL2 btw.

Also have a recommendation: for better artist accessibility IMO the blend files could be shared on Sketchfab, there's no easy way to use git-lfs (GitHub desktop doesn't provide any interface) and command line is usually a show stopper for artists. Also many tools / engines / platforms have [importers](https://sketchfab.com/importers) that make it seamless to share and use in our workflows. Plus it can help with discoverability!

**Comment by felixtrz** [comment]
Thank you for reporting this issue, I verified it just now and there is indeed a problem with files pushed to Github. I will open a task internally to get this resolved as soon as possible.

The accessibility aspect is also a good point. Though if the files were pushed correctly, regardless of whether lfs is enabled for this repo, people should be able to get everything by clicking Code -> Download Zip on the repo front page to its content.

**Comment by msub2** [comment]
Unfortunately downloading the repo zip directly still only gives you the LFS pointers, not the original files.

**Comment by felixtrz** [comment]
This issue should now be resolved, thank you @madjin again for flagging this.
