### ISSUE TITLE
Quest 2 is not recognized as VR device

### ISSUE THREAD

**Issue by Yonet** [meta-quest/ProjectFlowerbed#8]
Hi!
On quest 2 browser when I try to access project flower bed, I get the message if I want to send the experience to a VR device. This wasn't the case until recently. It seems like quest 2 is being considered as a mobile device.

**Comment by Yonet** [comment]
Looks like it is fixed.

**Comment by felixtrz** [comment]
Hi Yonet, thanks for flagging this. It's very strange, we didn't actually make any changes on project flowerbed recently. It looks like it's a transient issue for you, maybe a bad browser build. We will keep an eye on this.
